apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigo-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigo-config
  template:
    metadata:
      labels:
        app: sigo-config
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sigo-config
        image: docker.io/brunoferreirag/sigo-config:latest
        ports:
        - containerPort: 8000
          name: sigo-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  name: sigo-config
spec:
  selector:
    app: sigo-config
  ports:
    - protocol: HTTP
      port: 8000
      targetPort: 8000
      name: tcp-8000
---
