apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigo-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigo-config
  template:
    metadata:
      labels:
        app: sigo-config
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sigo-config
        image: docker.io/brunoferreirag/sigo-config:latest
        ports:
        - containerPort: 8000
          name: sigo-config
        resources:
          requests:
            cpu: 256m
          limits:
            cpu: 256m
---
apiVersion: v1
kind: Service
metadata:
  name: sigo-config
spec:
  ports:
  - port: 8000
  selector:
    app: sigo-config
---